name: family-connect-backend
services:
  - name: web
    dockerfile_path: Dockerfile.prod
    source_dir: /
    github:
      repo: rendijsb/family-connect-backend
      branch: main
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /ping  # Use simple ping endpoint instead of /health
    envs:
      - key: APP_NAME
        value: "Family Connect"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: "https://family-connect-9eh59.ondigitalocean.app"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
      - key: SESSION_DRIVER
        value: file  # Use file instead of database
      - key: CACHE_DRIVER
        value: file   # Use file instead of database
      - key: QUEUE_CONNECTION
        value: sync   # Use sync instead of database
      - key: BROADCAST_DRIVER
        value: log
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_DEFAULT_REGION
        value: eu-north-1
      - key: AWS_BUCKET
        value: netnest-images-production
      - key: AWS_URL
        value: "https://netnest-images-production.s3.amazonaws.com"
      - key: APP_VERSION
        value: "1.0.0-beta"
      - key: UPLOAD_MAX_FILESIZE
        value: "400M"
      - key: POST_MAX_SIZE
        value: "450M"
      - key: MAX_EXECUTION_TIME
        value: "300"
      - key: MEMORY_LIMIT
        value: "512M"
      - key: SUPPORT_EMAIL
        value: "support@yourapp.com"
      - key: PRIVACY_EMAIL
        value: "privacy@yourapp.com"
      - key: LEGAL_EMAIL
        value: "legal@yourapp.com"
      - key: ANDROID_APK_SIZE
        value: "50MB"
      - key: IOS_IPA_SIZE
        value: "60MB"
      # Database Configuration (SQLite for testing)
      - key: DB_CONNECTION
        value: "sqlite"
      - key: DB_DATABASE
        value: "/tmp/database.sqlite"
      # Secrets
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
